"""The register is current, and no NEW dead connection has appeared.

`REGISTER.md` is generated by `scripts/register.py`. This suite does the two
things that keep a generated document honest:

  1. REGENERATES AND BYTE-COMPARES. The owner's rule, 2026-08-31: *"in the
     same way we update all changes before switching threads, this document
     must be updated as well."* A register that can go stale is a register
     that will, which is precisely how `SYSTEMS-REFERENCE.md` came to name
     four of `campaign_email`'s seven `kb_needs` tokens.

  2. HOLDS THE FLAG LISTS TO A RATCHET. `KNOWN` is what was already true when
     the register was built. It may SHRINK and must never GROW — the same
     contract `test_sabotage_anchors.KNOWN_STALE` and the render suite's
     `ALLOWED_BARE` keep. A new EMPTY, DUPLICATE or CROSSOVER fails here, in
     the commit that created it, which is the only moment it is cheap.

Run: python3 scripts/test_register.py
"""
import json
import os
import pathlib
import subprocess
import sys
import tempfile

os.environ.setdefault(
    "DATABASE_URL", f"sqlite:///{os.path.join(tempfile.mkdtemp(), 'tr.db')}")
os.environ.setdefault("APPROVAL_SECRET", "s3cret")
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

#: Everything already flagged when the register was built (2026-08-31). Each
#: line is a real, named connection that goes nowhere or goes somewhere twice.
#: Delete a line when it is resolved; never add one.
KNOWN = {
    "empty": [
        "approval kind 'privacy_request' \u2014 created in shopify_webhooks.py, no executor arm",
        "approval kind 'skill_output' \u2014 created in skill.py, web.py, no executor arm",
        "approval kind 'sweep' \u2014 created in correlate.py, no executor arm",
        "disposition 'cleared' \u2014 no production module branches on it",
        "function baci_backoffice.py::list_company_documents \u2014 nothing references this name anywhere",
        "function canva.py::mcp_call \u2014 nothing references this name anywhere",
        "function constant_contact.py::send_test \u2014 nothing references this name anywhere",
        "function gmail_client.py::draft_exists \u2014 nothing references this name anywhere",
        "function model_error.py::is_operational \u2014 nothing references this name anywhere",
        "function omnisend.py::send_test \u2014 nothing references this name anywhere",
        "function ops_jobs.py::file_whatsapp_document \u2014 nothing references this name anywhere",
        "function portal.py::access_of \u2014 nothing references this name anywhere",
        "function propose.py::from_gap \u2014 nothing references this name anywhere",
        "function seo_tools.py::seo_context_block \u2014 nothing references this name anywhere",
        "function systems.py::account_key \u2014 nothing references this name anywhere",
        "system reorder_engine \u2014 declared empty \u2014 nothing performs this ship (ship: marks it launch-ready \u2014 launching stays human)",
        "system reports \u2014 declared empty \u2014 nothing performs this ship (ship: sends it to the client, on approval)"
    ],
    "duplicate": [
        "table ArtifactVersion has 2 writers and no declared owner: skill_pack.py, web.py",
        "table Deadline has 3 writers and no declared owner: ops_jobs.py, skills.py, worker.py",
        "table DocIndex has 2 writers and no declared owner: archive.py, data_tools.py",
        "table EmailLog has 2 writers and no declared owner: email_harvest.py, worker.py",
        "table FeedbackItem has 2 writers and no declared owner: skill_pack.py, web.py",
        "table Memory has 2 writers and no declared owner: memory.py, systems.py",
        "table Setting has 11 writers and no declared owner: canva.py, command_agent.py, email_harvest.py, ledger.py, ops_commands.py, ops_jobs.py, segments.py, skills.py, systems.py, web.py, worker.py",
        "table Tenant has 2 writers and no declared owner: tenants.py, web.py",
        "table User has 3 writers and no declared owner: portal.py, tenants.py, web.py",
        "table WaMessage has 2 writers and no declared owner: telegram.py, whatsapp.py"
    ],
    "crossover": [
        "table KbConflict is owned by kb.py and written by provenance.py",
        "table KbEmbedding is owned by kb.py and written by embed.py",
        "table KbEntity is owned by kb.py and written by catalog_sync.py"
    ]
}

_fail = []


def ck(label, cond, detail=""):
    print(f"[{'  ok  ' if cond else ' FAIL '}] {label}"
          + (f"  — {detail}" if detail else ""))
    if not cond:
        _fail.append(label)


def main() -> int:
    # COMPARED HERE, not delegated to `register.py --check`. Asking the thing
    # under test whether it is fine is the same species of mistake as the
    # sabotage harness reading stdout to decide whether a suite passed:
    # mutating the comparison inside `--check` to `if True` left this suite
    # green (sabotage reported MISSED, 2026-08-31). The suite does the compare.
    import register as _reg
    doc = ROOT / "REGISTER.md"
    ck("REGISTER.md exists", doc.exists(), str(doc))
    fresh = _reg.markdown(_reg.build()) if doc.exists() else ""
    ck("REGISTER.md is what the code says today",
       doc.exists() and doc.read_text() == fresh,
       "run python3 scripts/register.py --write")

    got = subprocess.run([sys.executable, str(ROOT / "scripts" / "register.py"),
                          "--json"], cwd=ROOT, capture_output=True, text=True)
    ck("the register computes", got.returncode == 0,
       (got.stderr or "").strip()[-160:])
    if got.returncode != 0:
        return 1
    reg = json.loads(got.stdout)

    for flag in ("empty", "duplicate", "crossover"):
        now, was = set(reg[flag]), set(KNOWN[flag])
        new = sorted(now - was)
        ck(f"no NEW {flag} connection", not new,
           "; ".join(new) or f"{len(now)} carried")
        gone = sorted(was - now)
        if gone:
            print(f"[  ok  ] {len(gone)} {flag} connection(s) RESOLVED — "
                  f"delete from KNOWN: {'; '.join(gone)}")

    ck("the register still says what it does not reach",
       len(reg["uncovered"]) >= 3,
       "a register silent about its edges reads as complete and is not")
    ck("every HTTP route is reached",
       all(r["reached"] for r in reg["routes"]),
       f"{sum(1 for r in reg['routes'] if not r['reached'])} unreached")

    print()
    if _fail:
        print(f"{len(_fail)} FAILED:")
        for f in _fail:
            print(f"  - {f}")
        return 1
    print(f"all checks passed — {len(reg['empty'])} empty, "
          f"{len(reg['duplicate'])} duplicate, {len(reg['crossover'])} "
          f"crossover, all known")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
